# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capsule < Formula
  desc "Terminal podcast client for Capsule"
  homepage "https://capsulefm.io"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Daio-io/capsule-releases/releases/download/v0.0.1/capsule_darwin_amd64.tar.gz"
    sha256 "533662ffdee3f733ede98fda9484334bc7d5b23b28192d9bb984d7b36f0bf7a6"

    define_method(:install) do
      bin.install "capsule"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Daio-io/capsule-releases/releases/download/v0.0.1/capsule_darwin_arm64.tar.gz"
    sha256 "3bff379558020b133cc196653e87b6d593c54fd646375d88a0d69cfb6cee5582"

    define_method(:install) do
      bin.install "capsule"
    end
  end

  test do
    system "#{bin}/capsule", "--version"
  end
end
