# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capsule < Formula
  desc "Terminal podcast client for Capsule"
  homepage "https://capsulefm.io"
  version "0.0.10"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Daio-io/homebrew-capsule-tap/releases/download/v0.0.10/capsule_darwin_amd64.tar.gz"
    sha256 "45d7efd14adfda2c9167abccc3b7e97d886934eb03b0888a16394cfc9d6da9b7"

    define_method(:install) do
      bin.install "capsule"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Daio-io/homebrew-capsule-tap/releases/download/v0.0.10/capsule_darwin_arm64.tar.gz"
    sha256 "0a8c38ef25cc61917b34f1e938b1f797849bd47db40f7a51ef525e74be594646"

    define_method(:install) do
      bin.install "capsule"
    end
  end

  test do
    system "#{bin}/capsule", "--version"
  end
end
